# Generated by Django 4.2.5 on 2023-09-24 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_copytrader_alter_cart_system_rename_systems_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Withdraw', 'Withdraw')], default='Not Paid', max_length=50)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.wallet', verbose_name='Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='SystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.system', verbose_name='System')),
            ],
        ),
    ]
