# Generated by Django 4.2.5 on 2023-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='twitch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='twitch_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Transfer', 'Transfer'), ('Withdraw', 'Withdraw')], default='Deposit', max_length=50),
        ),
    ]
