# Generated by Django 4.2.5 on 2023-10-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_chat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='LastProfit',
            new_name='copy_traders',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='LastProfitWinRate',
            new_name='last_profit',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='TotalCopyTraders',
            new_name='last_profit_win_rate',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='TotalProfits',
            new_name='max_drawdown',
        ),
        migrations.AddField(
            model_name='system',
            name='total_profits',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
