# Generated by Django 4.2.5 on 2023-10-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_rename_lastprofit_system_copy_traders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=160),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
