# Generated by Django 4.2.5 on 2023-10-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_service_slug_alter_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='pricing',
        ),
        migrations.AddField(
            model_name='system',
            name='fee',
            field=models.PositiveIntegerField(default=500, max_length=15),
        ),
    ]
