# Generated by Django 4.2.5 on 2023-10-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_system_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdata',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='systemdata',
            name='roi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
