# Generated by Django 4.2.5 on 2023-10-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='excel_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
